<?php
/**
 * ScaleWorks Bitcoin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@scaleworks.co so we can send you a copy immediately.
 *
 * @category    ScaleWorks
 * @package     ScaleWorks_Bitcoin
 * @copyright   Copyright (c) 2011 Ticean Bennett (http://www.scaleworks.co)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see ScaleWorks_Bitcoin_Block_Checkout_Onepage_Review_Payment
 */
?>
<?php if($this->getBitcoinPaymentAddress()): ?>
    <p>Thank you for using Bitcoin!</p>

    <p>Please be sure to submit payment to the provided address.</p>

    <!--
    <p><strong><?php echo $this->__('Send Bitcoin payment to:') ?></strong> <?php echo $this->htmlEscape($this->getBitcoinPaymentAddress()) ?></p>
    -->
<?php endif; ?>
