<?php
/**
 * ScaleWorks Bitcoin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@scaleworks.co so we can send you a copy immediately.
 *
 * @category    ScaleWorks
 * @package     ScaleWorks_Bitcoin
 * @copyright   Copyright (c) 2011 Ticean Bennett (http://www.scaleworks.co)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

 /** @see ScaleWorks_Bitcoin_Block_Adminhtml_Status */
?>
<h1>Bitcoin Status</h1>
<div>
    <?php if($this->getInfo()): ?>
        <p class="success">Connected to bitcoin service.</p>
        <table>
            <?php foreach($this->getInfo() as $key => $value): ?>
                <tr>
                    <td class="label"><?php echo $key ?></td><td class="value"><?php echo $value ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <p class="error">Could not connect to Bitcoin service.</p>
    <?php endif; ?>
</div>