<?php
/**
 * ScaleWorks Bitcoin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@scaleworks.co so we can send you a copy immediately.
 *
 * @category    ScaleWorks
 * @package     ScaleWorks_Bitcoin
 * @copyright   Copyright (c) 2011 Ticean Bennett (http://www.scaleworks.co)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see ScaleWorks_Bitcoin_Block_Payment_Info_Bitcoin
 */
?>
<style>
    div.payment-review {
        text-align: right;
        padding: 20px 5px;
        border: 1px solid #D9DDE3;
        border-width: 0 1px;
    }
    p.payment-address {
        font-size: 1.5em;
        font-weight: bold;
    }
</style>
<div class="payment-review">
    <p><?php echo $this->__('Please send Bitcoin payment to:') ?></p>
    <p class="payment-address"><?php echo $this->getBitcoinPaymentAddress(); ?></p>
</div>